### ISSUE TITLE
Need to rebuild toolchain with --disable-__cxa_atexit

### ISSUE THREAD

**Issue by igrr** [rogerclarkmelbourne/arduino-esp8266#2] opened 2015-03-30 17:59 UTC
As reported by @picstart on the esp8266 forum:
```
const int led = 2;
void setup() {
  // put your setup code here, to run once:
pinMode(led, OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(led, 1);
  
  delay(100);
  digitalWrite(led, 0);
   delay(100);
}
```

The above test (using mycode) is very very very simple and it works

This is a fresh install of Arduino on a win7 64 pro OS. I xxx'd out my folder in users/xxxxx
I downloaded from git hub a zip file arduino-esp8266-master-zip and unzipped it into User/xxxxx/Arduino/hardware
Now when I try the examples in this case hello world there are issues...__dso_handle is missing
Arduino: 1.6.2 (Windows 7), Board: "Generic ESP8266 board"
```
Build options changed, rebuilding all


HelloServer.cpp.o:(.text.startup+0x8): undefined reference to `__dso_handle'

c:/users/xxxx/documents/arduino/hardware/arduino-esp8266-master/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: C:\Users\Doug\AppData\Local\Temp\build5892183759428858024.tmp/HelloServer.cpp.elf: hidden symbol `__dso_handle' isn't defined

c:/users/xxxx/documents/arduino/hardware/arduino-esp8266-master/tools/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld.exe: final link failed: Bad value

collect2.exe: error: ld returned 1 exit status

Error compiling.
```

**Comment by rogerclarkmelbourne** [comment] 2015-03-30 20:33
Interesting

I will revert by local copy to SDK 0.9 and see if the issue pre exists

When I initially looked at SDK 1.0 using a different copy of the 1.0 SDK I got similar compile issues, so I wonder if this is a change in the SDK .

I will also download the full windows package 

Btw.

The other repo you linked to


https://github.com/sandeepmistry/esp8266-Arduino

May have the same issues as mine does, because basically its the same thing, I.e just repackaging esp8266com/arduino without the need for a full install

But he has franky done a better job than I have, as he has included OSX and Linux binaries

Well... Saying that. I'm not sure whether it would not be better to have separate repos for windows , Linux and OSX, to save downloading hundreds of MB of binaries for OSs , when people only need the binaries for their specific OS

**Comment by igrr** [comment] 2015-03-30 20:37
The __dso_handle issue is not an SDK issue, it's a toolchain issue. Until recently people were building the xtensa toolchain without --disable-__cxa_atexit, lack of which is the cause of this issue.

Regarding packaging, I don't think we need to have repositories for binaries. Just a script that would generate three packages (for Windows, Linux, and OS X).

**Comment by rogerclarkmelbourne** [comment] 2015-03-30 20:42
Ivan

Thanks

I will download the compiler package you linked to and confirm the cause


Btw. I totally agree.

All is needed is a script for each platform

**Comment by rogerclarkmelbourne** [comment] 2015-03-31 21:32
Ivan
I've tried to compile with the toolchain you use from http://download.igrr.me

But the toolchain compilation has the issue with not being able to locate libiconv-2.dll

Are these files that you compiled yourself ?

i.e is this your website ?

http://download.igrr.me/

I will see if I can put libiconv-2.dll in some other locations in the package, but I suspect the only place that may work is in the root of the IDE - which is no good

So the Xtensia compiler may need to be recompiled to get rid of this problem :-(

**Comment by rogerclarkmelbourne** [comment] 2015-03-31 21:54
Ivan

I've tried to see if I can put the DLL in the tools somewhere, but I cant get it to work at all, even putting the file in the Arduino IDE no longer works for me

I used the ARM libiconv-2.dll, but perhaps I should use the AVR one, but I suspect they are the same 

Can you send me a link to the docs to recompile GCC Win 32 again, so I can remove the issue with libiconv-2.dll ?

Or do you have a make file etc

**Comment by igrr** [comment] 2015-04-01 06:29
For windows I used something along these lines:
https://gist.github.com/fpoussin/7ae55b5a5bd9a28ce21d

If you build the toolchain, please build the x86(32-bit) version — lots of people are still not on x64.

**Comment by rogerclarkmelbourne** [comment] 2015-04-06 10:44
Ivan

Good point about 32 bit.

umm. I'll have to compile on a vitual machine using XP. But perhaps you have already done this.
I will check your issues list

**Comment by rogerclarkmelbourne** [comment] 2015-05-13 03:31
This has now been fixed in https://github.com/sandeepmistry/esp8266-Arduino

**Closed by rogerclarkmelbourne** 2015-05-13 03:31 UTC
